version: "3.8"
services:
  backend:
    build: ./server
    container_name: backend_c
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app
      - ./app/node_modules
    links:
      - redis-server
  frontend:
    build: ./client
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  redis-server:
    container_name: 'redis'
    image: 'redis:latest'
    ports:
     - "6379:6379"